#!/usr/bin/python3
# SPDX-License-Identifier: BSD-3-Clause
# SPDX-FileCopyrightText: 2025 Kota Matsura <s24c1110qm@s.chibakoudai.jp>
import sys
   
ans = 0.0
for line in sys.stdin:
    ans += float(line)
     
print(ans)
